//! Produce an *artifact of evidence* that the Layer-05 introspection surface
//! (`axiom-introspect`) works correctly against the real running engine.
//!
//! It drives the headless rotating-cube engine for a deterministic run,
//! interrogates `IntrospectApi` exactly as an agent would, and writes a
//! Markdown report of pass/fail checks to `target/introspection-evidence.md`
//! (also echoed to stdout). The process exits non-zero if any check fails, so
//! the artifact can be trusted and wired into CI.
//!
//! ```sh
//! cargo run -p axiom-demo-rotating-cube --example introspection_evidence
//! ```
//!
//! Checks:
//!   1. Live capture      — one report per tick, monotonic engine frame index.
//!   2. Query by index    — describe_frame returns the matching report.
//!   3. Snapshot channel  — snapshot_bytes() decodes back to an equal report.
//!   4. Deterministic     — two independent runs yield byte-identical snapshots.
//!   5. Per-system report — a frame whose step failed carries the system's
//!                          name + error code through serialization.

use std::fmt::Write as _;
use std::fs;

use axiom_demo_rotating_cube::DemoRotatingCubeApi;
use axiom_frame::FrameBuilder;
use axiom_host::{
    HostBoundaryConfig, HostFrameInput, HostLifecycleSignal, HostStepDriver, HostViewport,
};
use axiom_introspect::{FrameReport, IntrospectApi};
use axiom_kernel::HandleId;
use axiom_math::MathApi;
use axiom_runtime::{
    Runtime, RuntimeConfig, RuntimeContext, RuntimeError, RuntimeErrorCode, RuntimeResult,
    RuntimeSystem,
};

const TICKS: u64 = 120;
const OUT_PATH: &str = "target/introspection-evidence.md";

fn main() {
    let mut doc = String::new();
    let mut all_pass = true;
    let mut check = |doc: &mut String, label: &str, pass: bool| {
        all_pass &= pass;
        let _ = writeln!(doc, "- [{}] {label}", if pass { "PASS" } else { "FAIL" });
    };

    let _ = writeln!(doc, "# Axiom Introspection — Evidence Report\n");
    let _ = writeln!(
        doc,
        "Generated by `cargo run -p axiom-demo-rotating-cube --example \
         introspection_evidence`.\nDrives the headless rotating-cube engine and \
         interrogates the Layer-05 `axiom-introspect` `IntrospectApi`.\n"
    );

    // --- 1. Live capture over a deterministic run. ---
    let mut demo = DemoRotatingCubeApi::new();
    let mut indices = Vec::new();
    for tick in 0..=TICKS {
        indices.push(demo.run_tick(tick).engine_frame_index);
    }
    let recent = demo.recent_frames((TICKS + 1) as usize);
    let monotonic = indices.windows(2).all(|w| w[0] < w[1]);
    let _ = writeln!(doc, "## 1. Live capture over ticks 0..={TICKS}\n");
    let _ = writeln!(
        doc,
        "Frames retained: **{}** (history capacity is bounded).\n",
        recent.len()
    );
    let _ = writeln!(
        doc,
        "| engine_frame_index | host_frame_sequence | runtime_steps | lifecycle | viewport | systems |"
    );
    let _ = writeln!(doc, "|---|---|---|---|---|---|");
    for r in head_tail(recent, 3) {
        let _ = writeln!(
            doc,
            "| {} | {} | {} | {:?} | {}x{} | {} |",
            r.engine_frame_index(),
            r.host_frame_sequence(),
            r.runtime_step_count(),
            r.lifecycle(),
            r.viewport_width(),
            r.viewport_height(),
            r.systems().len(),
        );
    }
    let _ = writeln!(doc);
    check(&mut doc, "one report retained per tick", recent.len() == (TICKS + 1) as usize);
    check(&mut doc, "engine frame index is strictly monotonic", monotonic);

    // --- 2. Query by index. ---
    let _ = writeln!(doc, "\n## 2. Query by engine frame index\n");
    let probe = indices[60];
    let described = demo.describe_frame(probe);
    let described_ok = described.map(FrameReport::engine_frame_index) == Some(probe);
    let _ = writeln!(doc, "`describe_frame({probe})` -> index {described_ok}.");
    let missing_ok = demo.describe_frame(u64::MAX).is_none();
    check(&mut doc, "describe_frame returns the matching report", described_ok);
    check(&mut doc, "describe_frame misses an unobserved index", missing_ok);

    // --- 3. Serialized snapshot channel round-trips. ---
    let _ = writeln!(doc, "\n## 3. Serialized snapshot (the agent byte channel)\n");
    let snapshot = demo.introspection_snapshot().expect("a tick has run");
    let decoded = FrameReport::from_bytes(&snapshot).expect("snapshot decodes");
    let round_trips = Some(&decoded) == demo.recent_frames(1).first();
    let _ = writeln!(doc, "Latest snapshot: **{} bytes**.\n", snapshot.len());
    let _ = writeln!(doc, "```\n{}\n```\n", hex(&snapshot));
    check(&mut doc, "snapshot decodes back to an equal report", round_trips);

    // --- 4. Deterministic replay. ---
    let _ = writeln!(doc, "\n## 4. Deterministic replay\n");
    let run = |ticks: u64| {
        let mut d = DemoRotatingCubeApi::new();
        for t in 0..=ticks {
            d.run_tick(t);
        }
        d.introspection_snapshot().expect("a tick has run")
    };
    let snap_a = run(TICKS);
    let snap_b = run(TICKS);
    let identical = snap_a == snap_b;
    let _ = writeln!(
        doc,
        "Two independent runs of ticks 0..={TICKS} produce byte-identical \
         latest snapshots: **{identical}** ({} bytes each).",
        snap_a.len()
    );
    check(&mut doc, "independent runs are byte-identical (replayable)", identical);

    // --- 5. Per-system introspection via a failing system. ---
    let _ = writeln!(doc, "\n## 5. Per-system introspection (failing system)\n");
    let frame = failing_system_frame();
    let mut api = IntrospectApi::new(4);
    api.observe(&frame);
    let report = api.latest().expect("observed one frame");
    let sys = &report.systems()[0];
    let _ = writeln!(
        doc,
        "Observed a frame whose runtime step ran a failing system:\n\n\
         - system_id: `{}`\n- name: `{}`\n- order: `{}`\n- succeeded: `{}`\n- \
         error_code: `{:?}`\n",
        sys.system_id(),
        sys.name(),
        sys.order(),
        sys.succeeded(),
        sys.error_code(),
    );
    let sys_bytes = api.snapshot_bytes().expect("observed one frame");
    let sys_decoded = FrameReport::from_bytes(&sys_bytes).expect("decodes");
    check(&mut doc, "failing system is captured by name", sys.name() == "physics");
    check(&mut doc, "failure carries a non-empty error code", sys.error_code().is_some());
    check(
        &mut doc,
        "frame-with-system serializes and round-trips",
        sys_decoded.systems().len() == 1 && &sys_decoded == report,
    );

    // --- Verdict. ---
    let _ = writeln!(
        doc,
        "\n## Verdict\n\n**{}** — every introspection check above is satisfied \
         against the running engine.",
        if all_pass { "PASS" } else { "FAIL" }
    );

    fs::write(OUT_PATH, &doc).expect("write evidence artifact");
    print!("{doc}");
    println!("\nWrote evidence artifact to {OUT_PATH}");
    if !all_pass {
        std::process::exit(1);
    }
}

/// Build one engine frame whose single runtime step ran a failing system, so
/// its frame report carries a populated per-system report with an error code.
fn failing_system_frame() -> axiom_frame::EngineFrame {
    const STEP: u64 = 1_000;
    struct AlwaysFail;
    impl RuntimeSystem for AlwaysFail {
        fn run(&mut self, _: &mut RuntimeContext<'_>) -> RuntimeResult<()> {
            Err(RuntimeError::new(RuntimeErrorCode::SystemFailed, "boom"))
        }
    }
    let viewport = HostViewport::new(&MathApi::new(), 320, 200, 1.0).unwrap();
    let mut driver = HostStepDriver::new(HostBoundaryConfig::new(STEP, 5).unwrap());
    driver.apply_lifecycle_signal(HostLifecycleSignal::Started);
    let mut runtime =
        Runtime::new(RuntimeConfig::new(STEP).with_fail_on_system_error(false)).unwrap();
    runtime.initialize().unwrap();
    runtime.start().unwrap();
    runtime
        .scheduler_mut()
        .register(HandleId::from_raw(1), "physics", 1, Box::new(AlwaysFail))
        .unwrap();
    let report = driver
        .drive(&mut runtime, HostFrameInput::new(1, STEP, viewport))
        .unwrap();
    FrameBuilder::new(STEP).build(&report, Vec::new()).unwrap()
}

/// The first and last `n` reports of a slice (deduped if they overlap).
fn head_tail(reports: &[FrameReport], n: usize) -> Vec<&FrameReport> {
    let len = reports.len();
    let mut out: Vec<&FrameReport> = Vec::new();
    for (i, r) in reports.iter().enumerate() {
        if i < n || i >= len.saturating_sub(n) {
            out.push(r);
        }
    }
    out
}

/// Lowercase hex of a byte slice.
fn hex(bytes: &[u8]) -> String {
    let mut s = String::with_capacity(bytes.len() * 2);
    for b in bytes {
        let _ = write!(s, "{b:02x}");
    }
    s
}
