#![feature(rustc_private)]
#![warn(unused_extern_crates)]

// A list of available compiler crates can be found here:
// https://doc.rust-lang.org/nightly/nightly-rustc/
extern crate rustc_hir;

use clippy_utils::diagnostics::span_lint_and_help;
use clippy_utils::is_in_test;
use engine_lint_helpers::is_engine_file;
use rustc_hir::attrs::AttributeKind;
use rustc_hir::{Attribute, Item, ItemKind};
use rustc_lint::{LateContext, LateLintPass};

dylint_linting::declare_late_lint! {
    /// ### What it does
    ///
    /// Flags `pub mod` declarations in **engine source** (layer crates under
    /// `crates/` and modules under `modules/`) that have no doc comment.
    ///
    /// ### Why is this bad?
    ///
    /// Axiom is built for agentic development: an AI agent must be able to read
    /// the repository cold and immediately understand what each module owns and
    /// which layers it is allowed to depend on. A `pub mod foo {}` with no
    /// documentation is an unannounced black box — it slows down every agent,
    /// reviewer, and maintainer who opens it.
    ///
    /// Every public engine module must carry at least a one-liner explaining its
    /// responsibility and its allowed dependencies (consistent with the Module Law
    /// and the Layer Law in `CLAUDE.md`).
    ///
    /// ### Example
    ///
    /// ```rust
    /// // BAD — undocumented public module
    /// pub mod scene {}
    ///
    /// // GOOD — role and dependencies stated
    /// /// Scene graph and transform hierarchy. Depends only on the kernel and
    /// /// the math layer; imports nothing from other modules.
    /// pub mod scene {}
    ///
    /// // GOOD — inner doc comment is equally valid
    /// pub mod scene {
    ///     //! Scene graph and transform hierarchy.
    /// }
    /// ```
    ///
    /// Private modules are exempt — they are implementation detail and need not
    /// advertise themselves.
    pub ENGINE_REQUIRE_MODULE_DOCS,
    Warn,
    "public engine module without a doc comment"
}

/// Returns true when `attr` is any form of doc comment (`///`, `//!`, or
/// `#[doc = "..."]`). On this toolchain the HIR represents these as
/// `Attribute::Parsed(AttributeKind::DocComment { .. })`.
fn is_doc_comment(attr: &Attribute) -> bool {
    matches!(attr, Attribute::Parsed(AttributeKind::DocComment { .. }))
}

impl<'tcx> LateLintPass<'tcx> for EngineRequireModuleDocs {
    fn check_item(&mut self, cx: &LateContext<'tcx>, item: &'tcx Item<'tcx>) {
        // Only module items.
        let ItemKind::Mod(..) = item.kind else {
            return;
        };
        // Skip spans generated by macros.
        if item.span.from_expansion() {
            return;
        }
        // Tests may be undocumented.
        if is_in_test(cx.tcx, item.hir_id()) {
            return;
        }
        // Only engine spine files.
        if !is_engine_file(cx, item.span) {
            return;
        }
        // Only public modules.
        let def_id = item.owner_id.def_id;
        if !cx.tcx.visibility(def_id.to_def_id()).is_public() {
            return;
        }
        // Check for any doc comment attribute. `///` and `//!` both desugar to
        // `Attribute::Parsed(AttributeKind::DocComment { .. })` in HIR.
        let attrs = cx.tcx.hir_attrs(item.hir_id());
        let has_doc = attrs.iter().any(is_doc_comment);
        if has_doc {
            return;
        }
        span_lint_and_help(
            cx,
            ENGINE_REQUIRE_MODULE_DOCS,
            item.span,
            "this public engine module has no doc comment".to_string(),
            None,
            "add a `//!` (inside the module) or `///` (before the `mod`) comment stating the module's role and its allowed dependencies",
        );
    }
}

#[test]
fn ui() {
    dylint_testing::ui_test(env!("CARGO_PKG_NAME"), "ui");
}
