//! The rounded box — a box whose edges and corners are filleted.
//!
//! ## It is a sphere-swept box, and that is the whole construction
//!
//! A rounded box is exactly the **Minkowski sum of a box and a ball**: take the
//! box with half-extents `half_extents - corner_radius` (the *inset* box, the
//! set of legal sphere centres) and sweep a sphere of `corner_radius` over it.
//! Every point of the resulting surface satisfies one identity —
//!
//! ```text
//! distance(p, clamp(p, -inner, inner)) == corner_radius
//! normal(p)                            == (p - clamp(p, -inner, inner)) / corner_radius
//! ```
//!
//! — and that identity is what this generator emits, not an approximation of it.
//! The surface decomposes into 26 pieces by which part of the inset box is
//! nearest: **6 flat faces** (nearest point in a face interior), **12 quarter
//! cylinders** along the edges (nearest point on an edge), and **8 spherical
//! octants** at the corners (nearest point a vertex). Together they tile the
//! surface exactly once, meeting along shared arcs.
//!
//! ## Why 26 pieces and not one clever lattice
//!
//! A single direction-parameterised lattice looks tempting — the surface *is* a
//! function of the outward normal — but the flat faces each correspond to a
//! single direction, so they collapse to a point in that parameterisation and
//! have to be re-added as caps anyway. The 26-piece decomposition is the honest
//! shape of the object, and here it costs almost nothing: all 26 are generated by
//! **one** [`patch`] helper over `(u, v)`, differing only in the
//! `(position, normal)` function passed to it. There is no bespoke corner code,
//! no hand-written winding table, and no per-piece index arithmetic.
//!
//! Winding is resolved per quad by comparing the quad's geometric normal with
//! its analytic one, so mirrored octants come out counter-clockwise-front
//! without anybody deriving eight sign cases by hand. Zero-area quads — the
//! degenerate pole column of an octant, and every face and edge of a box whose
//! radius has eaten a whole half-extent — are dropped at emission rather than
//! shipped as junk triangles.
//!
//! Pieces meet on *bit-identical* expressions (a corner's `b = 0` arc and its
//! edge's arc are the same points reached from opposite ends), so the assembled
//! shell is already watertight; [`axiom_mesh::weld`] then merges the duplicated
//! seam vertices wherever their attributes agree. Seam vertices carry different
//! per-patch UVs by design — that is what an atlas unwrap *is* — so welding
//! tightens the vertex count without ever being load-bearing for the geometry.

use axiom_kernel::Meters;
use axiom_math::{Vec2, Vec3};
use axiom_mesh::{combine, weld, Mesh, MeshError, MeshErrorCode, MeshResult, MeshStreams};

use crate::tessellation::Segments;

/// The three world axes, indexed the way `Vec3`'s components are.
const AXES: [Vec3; 3] = [Vec3::UNIT_X, Vec3::UNIT_Y, Vec3::UNIT_Z];

/// A quad below this cross-product magnitude carries no surface and is dropped.
const PATCH_AREA_EPSILON: f32 = 1.0e-12;

/// Seam vertices agree to within a rounding error of the fillet radius; the weld
/// tolerance is that error, scaled to the radius, and far below the spacing of
/// two genuinely distinct arc samples at the maximum segment count.
const WELD_RELATIVE_TOLERANCE: f32 = 1.0e-4;

/// A box with `half_extents`, its twelve edges and eight corners rounded off at
/// `corner_radius`, tessellated with `segments` steps across each quarter-arc.
///
/// The result's bounds are exactly `±half_extents`: rounding eats into the box
/// rather than growing it.
///
/// # Errors
///
/// [`MeshErrorCode::InvalidParameter`] when any half-extent is non-finite or not
/// strictly positive, when `corner_radius` is not strictly positive, or when it
/// exceeds the smallest half-extent — beyond that there is no inset box left to
/// sweep and the requested shape does not exist. `corner_radius` exactly equal to
/// the smallest half-extent is legal and produces a fully-rounded axis; equal to
/// all three, a sphere.
pub fn rounded_box(
    half_extents: Vec3,
    corner_radius: Meters,
    segments: Segments,
) -> MeshResult<Mesh> {
    inset(half_extents, corner_radius)
        .and_then(|inner| pieces(inner, corner_radius.get(), segments))
        .and_then(|parts| combine(&parts))
        .and_then(|shell| {
            weld(
                &shell,
                Meters::finite_or_zero(corner_radius.get() * WELD_RELATIVE_TOLERANCE),
            )
        })
}

/// The inset box — the set of legal sphere centres — or the reason there is none.
fn inset(half_extents: Vec3, corner_radius: Meters) -> MeshResult<Vec3> {
    let h = half_extents;
    let finite = h.x.is_finite() & h.y.is_finite() & h.z.is_finite();
    let smallest = h.x.min(h.y).min(h.z);
    let radius = corner_radius.get();
    (finite & (smallest > 0.0) & (radius > 0.0) & (radius <= smallest))
        .then(|| Vec3::new(h.x - radius, h.y - radius, h.z - radius))
        .ok_or_else(|| {
            MeshError::new(
                MeshErrorCode::InvalidParameter,
                "a rounded box needs positive half-extents and a corner radius in (0, min half-extent]",
            )
        })
}

/// All 26 surface pieces, in a fixed order: corners, then edges, then faces.
fn pieces(inner: Vec3, radius: f32, segments: Segments) -> MeshResult<Vec<Mesh>> {
    let arc = segments.get();
    (0..8)
        .map(|corner| corner_patch(corner, inner, radius, arc))
        .chain((0..12).map(|edge| edge_patch(edge, inner, radius, arc)))
        .chain((0..6).map(|face| face_patch(face, inner, radius)))
        .collect()
}

/// `+1` for a clear bit, `-1` for a set one.
fn sign_of(bit: usize) -> f32 {
    1.0 - 2.0 * bit as f32
}

/// One component of a `Vec3`, chosen by index rather than by field.
fn component(v: Vec3, axis: usize) -> f32 {
    [v.x, v.y, v.z][axis]
}

/// One of the eight corner octants: a spherical patch centred on an inset-box
/// vertex. `u` runs from the `y` pole to the equator, `v` around it.
fn corner_patch(corner: usize, inner: Vec3, radius: f32, arc: u32) -> MeshResult<Mesh> {
    let signs = Vec3::new(
        sign_of(corner & 1),
        sign_of((corner >> 1) & 1),
        sign_of((corner >> 2) & 1),
    );
    let centre = Vec3::new(
        signs.x * inner.x,
        signs.y * inner.y,
        signs.z * inner.z,
    );
    patch(arc, arc, &|u, v| {
        let (polar, azimuth) = (
            u * core::f32::consts::FRAC_PI_2,
            v * core::f32::consts::FRAC_PI_2,
        );
        let normal = Vec3::new(
            signs.x * polar.sin() * azimuth.cos(),
            signs.y * polar.cos(),
            signs.z * polar.sin() * azimuth.sin(),
        );
        (centre.add(normal.mul_scalar(radius)), normal)
    })
}

/// One of the twelve edge fillets: a quarter cylinder about an inset-box edge.
/// `edge / 4` selects the axis the edge runs along, `edge % 4` which of the four
/// parallel edges. `u` runs around the quarter arc, `v` along the edge.
fn edge_patch(edge: usize, inner: Vec3, radius: f32, arc: u32) -> MeshResult<Mesh> {
    let along = edge / 4;
    let (first, second) = ((along + 1) % 3, (along + 2) % 3);
    let (s1, s2) = (sign_of(edge & 1), sign_of((edge >> 1) & 1));
    let anchor = AXES[first]
        .mul_scalar(s1 * component(inner, first))
        .add(AXES[second].mul_scalar(s2 * component(inner, second)));
    patch(arc, 1, &|u, v| {
        let angle = u * core::f32::consts::FRAC_PI_2;
        let normal = AXES[first]
            .mul_scalar(s1 * angle.cos())
            .add(AXES[second].mul_scalar(s2 * angle.sin()));
        let centre = anchor.add(
            AXES[along].mul_scalar(component(inner, along) * (2.0 * v - 1.0)),
        );
        (centre.add(normal.mul_scalar(radius)), normal)
    })
}

/// One of the six flat faces, inset by the radius on all four sides.
/// `face / 2` selects the axis, `face % 2` the side.
fn face_patch(face: usize, inner: Vec3, radius: f32) -> MeshResult<Mesh> {
    let axis = face / 2;
    let (first, second) = ((axis + 1) % 3, (axis + 2) % 3);
    let normal = AXES[axis].mul_scalar(sign_of(face & 1));
    let plane = normal.mul_scalar(component(inner, axis) + radius);
    patch(1, 1, &|u, v| {
        let centre = plane
            .add(AXES[first].mul_scalar(component(inner, first) * (2.0 * u - 1.0)))
            .add(AXES[second].mul_scalar(component(inner, second) * (2.0 * v - 1.0)));
        (centre, normal)
    })
}

/// The one grid builder every piece is made of.
///
/// `point(u, v)` returns the surface position and its analytic normal for
/// `u, v` in `0..=1`. Each cell's winding is chosen so its geometric normal
/// agrees with the analytic one, which is what lets the same code emit a patch
/// and its mirror image without a sign table. Zero-area cells are dropped.
fn patch(
    columns: u32,
    rows: u32,
    point: &dyn Fn(f32, f32) -> (Vec3, Vec3),
) -> MeshResult<Mesh> {
    let stride = (columns + 1) as usize;
    let grid: Vec<(Vec3, Vec3)> = (0..=rows)
        .flat_map(|row| (0..=columns).map(move |column| (column, row)))
        .map(|(column, row)| point(column as f32 / columns as f32, row as f32 / rows as f32))
        .collect();
    let positions: Vec<Vec3> = grid.iter().map(|(p, _)| *p).collect();
    let normals: Vec<Vec3> = grid.iter().map(|(_, n)| *n).collect();
    let uvs: Vec<Vec2> = (0..=rows)
        .flat_map(|row| (0..=columns).map(move |column| (column, row)))
        .map(|(column, row)| {
            Vec2::new(column as f32 / columns as f32, row as f32 / rows as f32)
        })
        .collect();
    let indices: Vec<u32> = (0..rows as usize)
        .flat_map(|row| (0..columns as usize).map(move |column| (column, row)))
        .flat_map(|(column, row)| {
            let a = (row * stride + column) as u32;
            let (b, c, d) = (a + 1, a + 1 + stride as u32, a + stride as u32);
            let analytic = [a, b, c, d]
                .iter()
                .fold(Vec3::ZERO, |acc, i| acc.add(normals[*i as usize]));
            let geometric = positions[b as usize]
                .subtract(positions[a as usize])
                .cross(positions[c as usize].subtract(positions[a as usize]));
            let forward = usize::from(geometric.dot(analytic) >= 0.0);
            [
                [[a, c, b], [a, b, c]][forward],
                [[a, d, c], [a, c, d]][forward],
            ]
        })
        .filter(|t| spans_area(&positions, t))
        .flatten()
        .collect();
    Mesh::from_streams(MeshStreams {
        normals,
        uvs,
        ..MeshStreams::new(positions, indices)
    })
}

/// Whether a triangle encloses any area at all.
fn spans_area(positions: &[Vec3], triangle: &[u32; 3]) -> bool {
    let (a, b, c) = (
        positions[triangle[0] as usize],
        positions[triangle[1] as usize],
        positions[triangle[2] as usize],
    );
    b.subtract(a).cross(c.subtract(a)).length_squared() > PATCH_AREA_EPSILON
}

#[cfg(test)]
mod tests {
    use super::*;

    fn meters(v: f32) -> Meters {
        Meters::new(v).unwrap()
    }

    fn segments(n: u32) -> Segments {
        Segments::new(n).unwrap()
    }

    /// The nearest point of the inset box to `p` — the sphere centre that
    /// generated it.
    fn clamp_to(p: Vec3, inner: Vec3) -> Vec3 {
        Vec3::new(
            p.x.clamp(-inner.x, inner.x),
            p.y.clamp(-inner.y, inner.y),
            p.z.clamp(-inner.z, inner.z),
        )
    }

    fn bounds(mesh: &Mesh) -> (Vec3, Vec3) {
        mesh.positions().iter().fold(
            (
                Vec3::new(f32::INFINITY, f32::INFINITY, f32::INFINITY),
                Vec3::new(f32::NEG_INFINITY, f32::NEG_INFINITY, f32::NEG_INFINITY),
            ),
            |(lo, hi), p| {
                (
                    Vec3::new(lo.x.min(p.x), lo.y.min(p.y), lo.z.min(p.z)),
                    Vec3::new(hi.x.max(p.x), hi.y.max(p.y), hi.z.max(p.z)),
                )
            },
        )
    }

    fn surface_area(mesh: &Mesh) -> f32 {
        mesh.indices()
            .chunks(3)
            .map(|t| {
                let p = mesh.positions();
                let (a, b, c) = (p[t[0] as usize], p[t[1] as usize], p[t[2] as usize]);
                b.subtract(a).cross(c.subtract(a)).length() * 0.5
            })
            .sum()
    }

    fn faces_outward(mesh: &Mesh) -> bool {
        mesh.indices().chunks(3).all(|t| {
            let p = mesh.positions();
            let (a, b, c) = (p[t[0] as usize], p[t[1] as usize], p[t[2] as usize]);
            let centroid = a.add(b).add(c).mul_scalar(1.0 / 3.0);
            let geometric = b.subtract(a).cross(c.subtract(a));
            geometric.length() < 1.0e-9 || geometric.dot(centroid) > 0.0
        })
    }

    #[test]
    fn every_vertex_lies_exactly_one_radius_off_the_inset_box() {
        let half = Vec3::new(2.0, 1.0, 3.0);
        let radius = 0.4;
        let mesh = rounded_box(half, meters(radius), segments(6)).unwrap();
        let inner = Vec3::new(half.x - radius, half.y - radius, half.z - radius);
        for p in mesh.positions() {
            let offset = p.subtract(clamp_to(*p, inner)).length();
            assert!(
                (offset - radius).abs() < 1.0e-4,
                "vertex {p:?} sits {offset} from the inset box, not {radius}"
            );
        }
    }

    #[test]
    fn every_normal_points_away_from_the_nearest_inset_box_point() {
        let half = Vec3::new(2.0, 1.5, 1.0);
        let radius = 0.3;
        let mesh = rounded_box(half, meters(radius), segments(5)).unwrap();
        let inner = Vec3::new(half.x - radius, half.y - radius, half.z - radius);
        for (p, n) in mesh.positions().iter().zip(mesh.normals()) {
            let expected = p.subtract(clamp_to(*p, inner)).mul_scalar(1.0 / radius);
            assert!(
                n.subtract(expected).length() < 1.0e-4,
                "normal {n:?} at {p:?} should have been {expected:?}"
            );
            assert!((n.length() - 1.0).abs() < 1.0e-4);
        }
    }

    #[test]
    fn the_bounds_are_exactly_the_half_extents() {
        let half = Vec3::new(2.0, 1.0, 3.0);
        let mesh = rounded_box(half, meters(0.5), segments(8)).unwrap();
        let (lo, hi) = bounds(&mesh);
        assert!(hi.subtract(half).length() < 1.0e-5, "high bound {hi:?}");
        assert!(lo.add(half).length() < 1.0e-5, "low bound {lo:?}");
    }

    #[test]
    fn the_surface_area_matches_the_minkowski_sum_of_a_box_and_a_ball() {
        // A(box (+) ball) = 8(ab + bc + ca) + 4*pi*r*(a + b + c) + 4*pi*r^2,
        // with a, b, c the inset half-extents.
        let half = Vec3::new(2.0, 1.5, 1.0);
        let r = 0.25;
        let (a, b, c) = (half.x - r, half.y - r, half.z - r);
        let expected = 8.0 * (a * b + b * c + c * a)
            + 4.0 * core::f32::consts::PI * r * (a + b + c)
            + 4.0 * core::f32::consts::PI * r * r;
        let measured = surface_area(&rounded_box(half, meters(r), segments(24)).unwrap());
        assert!(
            (measured - expected).abs() / expected < 0.01,
            "area {measured}, expected {expected}"
        );
    }

    #[test]
    fn every_triangle_faces_outward() {
        // A rounded box is convex, so the origin is inside every face's plane.
        let mesh = rounded_box(Vec3::new(1.0, 2.0, 1.5), meters(0.35), segments(5)).unwrap();
        assert!(faces_outward(&mesh));
    }

    #[test]
    fn no_triangle_is_degenerate() {
        let mesh = rounded_box(Vec3::new(1.0, 1.0, 1.0), meters(0.25), segments(4)).unwrap();
        assert!(mesh.triangle_count() > 0);
        for t in mesh.indices().chunks(3) {
            let p = mesh.positions();
            let (a, b, c) = (p[t[0] as usize], p[t[1] as usize], p[t[2] as usize]);
            assert!(b.subtract(a).cross(c.subtract(a)).length() > 1.0e-7);
        }
    }

    #[test]
    fn a_radius_equal_to_every_half_extent_is_a_sphere() {
        let mesh = rounded_box(Vec3::new(1.0, 1.0, 1.0), meters(1.0), segments(12)).unwrap();
        for p in mesh.positions() {
            let radius = p.length();
            assert!((radius - 1.0).abs() < 1.0e-4, "off-sphere radius {radius}");
        }
        let measured = surface_area(&mesh);
        let expected = 4.0 * core::f32::consts::PI;
        assert!((measured - expected).abs() / expected < 0.02);
        assert!(faces_outward(&mesh));
    }

    #[test]
    fn a_radius_equal_to_the_smallest_half_extent_rounds_that_axis_away() {
        let half = Vec3::new(3.0, 0.5, 2.0);
        let mesh = rounded_box(half, meters(0.5), segments(8)).unwrap();
        let (lo, hi) = bounds(&mesh);
        assert!(hi.subtract(half).length() < 1.0e-5);
        assert!(lo.add(half).length() < 1.0e-5);
        assert!(faces_outward(&mesh));
    }

    #[test]
    fn a_radius_larger_than_the_smallest_half_extent_is_an_invalid_parameter() {
        assert_eq!(
            rounded_box(Vec3::new(2.0, 0.5, 2.0), meters(0.6), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
    }

    #[test]
    fn a_non_positive_radius_is_an_invalid_parameter() {
        assert_eq!(
            rounded_box(Vec3::ONE, meters(0.0), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
        assert_eq!(
            rounded_box(Vec3::ONE, meters(-0.2), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
    }

    #[test]
    fn a_non_positive_half_extent_is_an_invalid_parameter() {
        assert_eq!(
            rounded_box(Vec3::new(1.0, 0.0, 1.0), meters(0.1), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
        assert_eq!(
            rounded_box(Vec3::new(1.0, -1.0, 1.0), meters(0.1), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
    }

    #[test]
    fn a_non_finite_half_extent_is_an_invalid_parameter() {
        assert_eq!(
            rounded_box(Vec3::new(f32::NAN, 1.0, 1.0), meters(0.1), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
        assert_eq!(
            rounded_box(Vec3::new(1.0, f32::INFINITY, 1.0), meters(0.1), segments(4))
                .unwrap_err()
                .code(),
            MeshErrorCode::InvalidParameter
        );
    }

    #[test]
    fn uvs_cover_the_unit_square_on_every_piece() {
        let mesh = rounded_box(Vec3::new(1.0, 1.0, 1.0), meters(0.3), segments(4)).unwrap();
        assert!(mesh.has_uvs());
        assert!(mesh.has_normals());
        for uv in mesh.uvs() {
            assert!(uv.x >= -1.0e-6 && uv.x <= 1.0 + 1.0e-6);
            assert!(uv.y >= -1.0e-6 && uv.y <= 1.0 + 1.0e-6);
        }
    }

    #[test]
    fn a_rounded_box_is_reproducible() {
        let build =
            || rounded_box(Vec3::new(1.0, 2.0, 0.75), meters(0.2), segments(7)).unwrap();
        assert_eq!(build(), build());
    }

    #[test]
    fn more_segments_mean_more_geometry_and_a_tighter_area() {
        let half = Vec3::new(1.0, 1.0, 1.0);
        let coarse = rounded_box(half, meters(0.4), segments(3)).unwrap();
        let fine = rounded_box(half, meters(0.4), segments(12)).unwrap();
        assert!(fine.triangle_count() > coarse.triangle_count());
        // A polygonal fillet under-measures the true area; refining converges up.
        assert!(surface_area(&fine) > surface_area(&coarse));
    }
}
