#!/usr/bin/env python3
"""Assemble the multi-app demo gallery into ``dist/``.

Repo tooling (alongside ``package_app.py`` and the Makefile), NOT part of the engine
dependency graph. The gallery de-merge split every Rust browser demo back out into
its own standalone app crate (``apps/axiom-<id>``); ``apps/axiom-gallery`` keeps ONLY
a static ``web/`` shell (the landing grid ``index.html`` + ``gallery.js`` +
``styles.css`` and the committed pure-TS single-file pages like home-run/heat-check).
The gallery site is therefore the static shell plus one PER-DEMO bundle per extracted
app, each self-contained under ``dist/<id>/``.

It does two things:

1. **Copy the static site** ``apps/axiom-gallery/web/`` -> ``dist/`` verbatim (minus
   any stray local ``pkg/`` build output) — the shell and every committed pure-TS
   single-file page.

2. **Build each demo app's bundle** under ``dist/<id>/`` via
   ``package_app.build_bundle`` + ``package_app.emit_index_html``: the app's own
   ``web/`` assets (minus ``pkg/``), a size-optimized wasm fast-path AND (unless
   ``--fast``) a Binaryen wasm2js fallback, behind a per-app ``dist/<id>/
   axiom-loader.js``, with the copied page's ``./pkg/axiom_<snake>.js`` import
   rewritten to ``./axiom-loader.js``. The netplay app's vendored ``@axiom/client``
   SDK (``apps/axiom-netplay/web/vendor/axiom-client``, generated by ``make
   netplay-build``) simply rides along in that copy when present — exactly as the
   old single-bundle flow rode the Makefile-vendored dir.

The full build rebuilds std MVP once into a target dir SHARED across all demo builds
(so the wasm2js fallback is possible — see ``package_app.py``), so the first
``make gallery`` is slow; re-runs are incremental. ``--fast`` skips the fallback for
tight iteration, and ``--only <id> [...]`` rebuilds a subset of demos.
"""

from __future__ import annotations

import argparse
import shutil
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
import package_app  # noqa: E402  (local repo tooling, not an installed package)

REPO_ROOT = Path(__file__).resolve().parent.parent
GALLERY_WEB = REPO_ROOT / "apps" / "axiom-gallery" / "web"

# The extracted standalone demo apps: (gallery page id -> apps/axiom-<id> crate).
# Each ships its own web/index.html importing ./pkg/axiom_<snake>.js, which the
# per-app packaging rewrites to the bundle-root ./axiom-loader.js.
DEMO_APPS: list[str] = [
    "rotating-cube",
    "netplay",
    "retro-fps",
    "stress-cubes",
    "physics-crucible",
    "gravix",
    "sports-physics-lab",
    "dev-harness",
    "growth",
    "generia",
    "zanzoban",
    "quintet",
    "forest-walk",
]


def demo_app_dir(demo_id: str) -> Path:
    return REPO_ROOT / "apps" / f"axiom-{demo_id}"


def copy_gallery_static(dist: Path) -> None:
    """Lay the gallery's static shell over ``dist/``. Skip any stray local build
    output (a ``pkg/`` left by a standalone wasm-bindgen run) AND any leftover
    per-demo page dir named after an extracted app — those pages now ship with
    their own apps and are built under ``dist/<id>/`` by ``build_demo_apps``."""
    if not (GALLERY_WEB / "index.html").is_file():
        sys.exit(f"error: {GALLERY_WEB} not found — the gallery static site is missing.")
    for item in GALLERY_WEB.iterdir():
        if item.name == "pkg" or item.name in DEMO_APPS:
            continue
        dest = dist / item.name
        if item.is_dir():
            shutil.copytree(item, dest, dirs_exist_ok=True)
        else:
            shutil.copy2(item, dest)


def build_demo_apps(
    dist: Path,
    *,
    fast: bool,
    target_dir: Path,
    debug: bool = False,
    only: list[str] | None = None,
) -> None:
    """Build every extracted demo app's bundle into ``dist/<id>/``: copy the app's
    ``web/`` (minus ``pkg/``), build the per-app loader + wasm beside the page, and
    rewrite the page's glue import to ``./axiom-loader.js``. The ``target_dir`` is
    shared across all builds so std/deps compile once. Also reused by
    ``package_workspace.py`` for its ``dist-workspace/gallery/`` tree."""
    ids = DEMO_APPS if only is None else only
    unknown = [i for i in ids if i not in DEMO_APPS]
    if unknown:
        sys.exit(f"error: unknown demo id(s) {', '.join(unknown)} — known: {', '.join(DEMO_APPS)}")
    for demo_id in ids:
        app_dir = demo_app_dir(demo_id)
        if not (app_dir / "web" / "index.html").is_file():
            sys.exit(f"error: {app_dir}/web/index.html not found — the {demo_id} app is missing.")
        out = dist / demo_id
        print(f"\n[{demo_id}] building bundle into {out}{' (fast: wasm-only)' if fast else ''}")
        snake = package_app.build_bundle(app_dir, out, fast=fast, target_dir=target_dir, debug=debug)
        # Copy the app's web/ assets (minus pkg/) beside the bundle and rewrite the
        # page's ./pkg/<snake>.js glue import to ./axiom-loader.js. The netplay
        # vendor/ dir (when `make netplay-build` has generated it) rides along here.
        package_app.emit_index_html(app_dir, out, snake, sdk_hosted=False)


def _dir_size_mb(path: Path) -> float:
    return sum(f.stat().st_size for f in path.rglob("*") if f.is_file()) / (1024 * 1024)


def main() -> int:
    parser = argparse.ArgumentParser(description="Package the multi-app demo gallery into dist/.")
    parser.add_argument(
        "--fast",
        action="store_true",
        help="quick wasm-only bundles (normal incremental build, no wasm2js fallback) for iteration",
    )
    parser.add_argument(
        "--debug",
        action="store_true",
        help="debug wasm builds (keeps debug_assertions on for the Canvas2D deep profiler; "
        "used by the render benchmark). Implies --fast (no wasm2js fallback).",
    )
    parser.add_argument(
        "--only",
        nargs="+",
        metavar="ID",
        help="build only these demo app bundles (still lays the full static shell); "
        f"known ids: {', '.join(DEMO_APPS)}",
    )
    args = parser.parse_args()
    if args.debug:
        args.fast = True

    if not (GALLERY_WEB / "index.html").is_file():
        sys.exit(f"error: {GALLERY_WEB} not found — the gallery static site is missing.")

    dist = REPO_ROOT / "dist"
    if dist.exists():
        shutil.rmtree(dist)
    dist.mkdir(parents=True)

    # 1. The static shell (landing grid + pure-TS single-file pages) over dist/.
    copy_gallery_static(dist)

    # 2. One self-contained bundle per extracted demo app under dist/<id>/.
    #    fast shares the main target dir (incremental); full uses the MVP build dir,
    #    shared across all 13 builds so std compiles once.
    target_dir = (REPO_ROOT / "target") if args.fast else (REPO_ROOT / "target" / "package-mvp")
    build_demo_apps(dist, fast=args.fast, target_dir=target_dir, debug=args.debug, only=args.only)

    # 3. Re-lay the static shell (index.html/gallery.js may have changed while the
    #    slow wasm builds ran; the shell copy is cheap and idempotent). App pages
    #    under dist/<id>/ are NOT touched — the shell owns no <id>/ dirs anymore.
    copy_gallery_static(dist)

    print(f"\nassembled the multi-app gallery into {dist}  ({_dir_size_mb(dist):.0f} MB total)")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
