/*
 * visual-profiles.ts — presentation-only data, kept entirely separate from
 * card rules. One normal/forged profile pair is authored per group (plus one
 * pair for the neutral cards), and every card of that group points its
 * `visualProfile` / `forgedVisualProfile` at the shared pair — the
 * "manageable" reuse pattern: ids are real, referenced, and validated, and
 * a forged profile is always a strictly stronger presentation (bigger
 * particle budget, richer sound cues, upgraded asset keys) than its normal
 * counterpart. Bloomtide's tokens reuse the Bloomtide pair, since sprouts are
 * a direct expression of the same grove.
 */

import type { VisualProfile } from "./schema.ts";

export const VISUAL_PROFILES: readonly VisualProfile[] = [
  // ── Ironbound ────────────────────────────────────────────────────────────
  {
    id: "vp_ironbound_normal",
    frame: "frame_ironbound_riveted",
    portrait: "portrait_ironbound_worker",
    border: "border_ironbound_bronze",
    base: "base_ironbound_plate",
    idle: "idle_ironbound_stance",
    entrance: "entrance_ironbound_drop",
    attackTrail: "trail_ironbound_swing",
    impact: "impact_ironbound_clang",
    death: "death_ironbound_collapse",
    aura: "aura_ironbound_none",
    groupColor: "#7C8A99",
    particleBudget: 12,
    soundCues: ["clank_low", "hydraulic_hiss"],
  },
  {
    id: "vp_ironbound_forged",
    frame: "frame_ironbound_masterforged",
    portrait: "portrait_ironbound_champion",
    border: "border_ironbound_gold_rivet",
    base: "base_ironbound_plate_glowing",
    idle: "idle_ironbound_stance_charged",
    entrance: "entrance_ironbound_slam",
    attackTrail: "trail_ironbound_swing_sparkburst",
    impact: "impact_ironbound_clang_heavy",
    death: "death_ironbound_shatter",
    aura: "aura_ironbound_ember_seam",
    groupColor: "#7C8A99",
    particleBudget: 24,
    soundCues: ["clank_heavy", "hydraulic_hiss_deep", "forge_ring"],
  },
  // ── Emberkin ─────────────────────────────────────────────────────────────
  {
    id: "vp_emberkin_normal",
    frame: "frame_emberkin_cracked",
    portrait: "portrait_emberkin_duelist",
    border: "border_emberkin_cinder",
    base: "base_emberkin_magma_skin",
    idle: "idle_emberkin_smolder",
    entrance: "entrance_emberkin_flare_step",
    attackTrail: "trail_emberkin_ember_arc",
    impact: "impact_emberkin_scorch",
    death: "death_emberkin_ash_collapse",
    aura: "aura_emberkin_heat_shimmer",
    groupColor: "#E2572B",
    particleBudget: 16,
    soundCues: ["fire_crackle", "ember_hiss"],
  },
  {
    id: "vp_emberkin_forged",
    frame: "frame_emberkin_infernal",
    portrait: "portrait_emberkin_champion",
    border: "border_emberkin_molten_gold",
    base: "base_emberkin_magma_skin_bright",
    idle: "idle_emberkin_roiling_flame",
    entrance: "entrance_emberkin_ignition_burst",
    attackTrail: "trail_emberkin_inferno_arc",
    impact: "impact_emberkin_detonation",
    death: "death_emberkin_supernova",
    aura: "aura_emberkin_firestorm",
    groupColor: "#E2572B",
    particleBudget: 32,
    soundCues: ["fire_roar", "ember_hiss_deep", "explosion_crack"],
  },
  // ── Bloomtide ────────────────────────────────────────────────────────────
  {
    id: "vp_bloomtide_normal",
    frame: "frame_bloomtide_bark",
    portrait: "portrait_bloomtide_sprout_tender",
    border: "border_bloomtide_vine",
    base: "base_bloomtide_root_plate",
    idle: "idle_bloomtide_sway",
    entrance: "entrance_bloomtide_unfurl",
    attackTrail: "trail_bloomtide_thorn_lash",
    impact: "impact_bloomtide_petal_burst",
    death: "death_bloomtide_wilt",
    aura: "aura_bloomtide_spore_drift",
    groupColor: "#3FAE64",
    particleBudget: 14,
    soundCues: ["root_creak", "leaf_rustle"],
  },
  {
    id: "vp_bloomtide_forged",
    frame: "frame_bloomtide_ancient_bark",
    portrait: "portrait_bloomtide_grove_elder",
    border: "border_bloomtide_gold_vine",
    base: "base_bloomtide_root_plate_luminous",
    idle: "idle_bloomtide_bloom_pulse",
    entrance: "entrance_bloomtide_canopy_bloom",
    attackTrail: "trail_bloomtide_bramble_lash",
    impact: "impact_bloomtide_seedburst",
    death: "death_bloomtide_scatter_seeds",
    aura: "aura_bloomtide_pollen_storm",
    groupColor: "#3FAE64",
    particleBudget: 28,
    soundCues: ["root_groan_deep", "leaf_rustle_heavy", "petal_chime"],
  },
  // ── Echowisp ─────────────────────────────────────────────────────────────
  {
    id: "vp_echowisp_normal",
    frame: "frame_echowisp_afterimage",
    portrait: "portrait_echowisp_trickster",
    border: "border_echowisp_violet_flicker",
    base: "base_echowisp_translucent",
    idle: "idle_echowisp_shimmer",
    entrance: "entrance_echowisp_blink_in",
    attackTrail: "trail_echowisp_afterimage_smear",
    impact: "impact_echowisp_refraction",
    death: "death_echowisp_fade_out",
    aura: "aura_echowisp_light_bend",
    groupColor: "#9B6BD1",
    particleBudget: 15,
    soundCues: ["chime_light", "whisper_echo"],
  },
  {
    id: "vp_echowisp_forged",
    frame: "frame_echowisp_prism",
    portrait: "portrait_echowisp_archmirror",
    border: "border_echowisp_gold_prism",
    base: "base_echowisp_radiant_translucent",
    idle: "idle_echowisp_double_shimmer",
    entrance: "entrance_echowisp_mirror_split",
    attackTrail: "trail_echowisp_prism_smear",
    impact: "impact_echowisp_shatter_light",
    death: "death_echowisp_scatter_reflections",
    aura: "aura_echowisp_kaleidoscope",
    groupColor: "#9B6BD1",
    particleBudget: 30,
    soundCues: ["chime_resonant", "whisper_echo_chorus", "glass_shimmer"],
  },
  // ── Neutral ──────────────────────────────────────────────────────────────
  {
    id: "vp_neutral_normal",
    frame: "frame_neutral_plain",
    portrait: "portrait_neutral_wanderer",
    border: "border_neutral_iron",
    base: "base_neutral_traveler_garb",
    idle: "idle_neutral_stand",
    entrance: "entrance_neutral_step_in",
    attackTrail: "trail_neutral_swing",
    impact: "impact_neutral_thud",
    death: "death_neutral_collapse",
    aura: "aura_neutral_none",
    groupColor: "#B8B2A1",
    particleBudget: 8,
    soundCues: ["thud_soft"],
  },
  {
    id: "vp_neutral_forged",
    frame: "frame_neutral_engraved",
    portrait: "portrait_neutral_journeyman",
    border: "border_neutral_polished_iron",
    base: "base_neutral_traveler_garb_trimmed",
    idle: "idle_neutral_confident_stand",
    entrance: "entrance_neutral_stride_in",
    attackTrail: "trail_neutral_swing_gleam",
    impact: "impact_neutral_thud_heavy",
    death: "death_neutral_kneel_fade",
    aura: "aura_neutral_faint_gleam",
    groupColor: "#B8B2A1",
    particleBudget: 14,
    soundCues: ["thud_firm", "coin_clink"],
  },
];
