//! # Axiom Soccer Penalty — App (Stage 1: static diorama)
//!
//! A deterministic, fixed-camera, retro 32-bit-style soccer penalty-kick **static
//! diorama**. Stage 1 exists to *establish the game visually* before any
//! gameplay exists: it builds a fixed scene — kicker behind the ball, ball on
//! the penalty spot, goalie in the goal, posts + net, a lined field, a stadium
//! wall with a fake crowd and ad boards, and a chunky arcade HUD — and nothing
//! moves.
//!
//! ## Why this is an app, not a layer or module
//! This is a *composition leaf*. It invents no reusable engine capability: it
//! only arranges fixed data (positions, sizes, colors, HUD values) into a
//! diorama descriptor and an ordered render plan. Its sole engine dependency is
//! the **math** layer's public [`axiom_math::Vec3`] facade, used for every
//! spatial quantity. Soccer, goalie, shot, score, and HUD concepts live here
//! and *only* here — never in the kernel, runtime, math, scene, or render
//! layers.
//!
//! ## Recipe-generated art (no hand-authored geometry or pixels)
//! Every mesh and texture the scene draws is **generated by the recipe pipeline**
//! (`axiom-recipe` + `axiom-proc-mesh` + `axiom-proc-texture`), mirroring
//! `examples/recipes/generated_micro_fps`. [`recipe_style`] holds the one seed +
//! palette; [`recipe_meshes`] are the mesh operator graphs (box, sphere, capsule);
//! [`recipe_textures`] are the texture operator graphs (crowd, kits, ad boards,
//! ball, skin). [`penalty_render_meshed`] bakes them once through `ProcMeshApi` /
//! `ProcTextureApi` and registers the results via the ordinary `add_mesh_data` /
//! `add_texture_data` hooks — the app authors no vertices or pixels of its own.
//! (The old hand-authored `penalty_meshes` / `penalty_textures` are deleted.) Two
//! operators were added to the recipe layers to close the last fidelity gaps at
//! the correct layer rather than approximate in the app: a `Sphere` mesh op
//! (`axiom-proc-mesh`) so the ball and heads are truly round, and a `Text` texture
//! op (`axiom-proc-texture`) so the jersey number and the "AXIOM"/"SPORTS" ad
//! boards read as real lettering.
//!
//! ## Temporary app glue
//! Axiom has no soccer asset/mesh-part module, so the smallest deterministic data
//! shapes the diorama needs — [`low_poly_assets`] primitives + palette, the
//! [`penalty_scene`] object model, the [`penalty_hud`] model, and the
//! [`penalty_render_plan`] ordering model — are defined app-locally, then bound to
//! the recipe-baked resources by [`penalty_render_meshed`]. See `STAGE_1.md` and
//! `PASS_2_DEPTH_ORDERING.md`.
//!
//! ## Pass 2 — deterministic depth ordering and net layering
//! [`penalty_render_plan`] adds the app's render-ordering model:
//! [`penalty_render_plan::PenaltyDrawLayer`] (14 explicit back-to-front
//! buckets), a [`penalty_render_plan::PenaltySortKey`] of
//! `(layer, coarse depth bucket, stable object ordinal)`, and a total sort into
//! [`penalty_render_plan::PenaltyRenderPlan`]. The net is split into rear/front
//! layers so it reads with real depth around the actors.
//!
//! ## Pass 3 — deterministic lighting, materials, blob shadows, retro 32-bit style
//! [`penalty_light::PenaltyLightModel`] is a fixed flat-shading model
//! (ambient + directional, quantized into fixed brightness bands).
//! [`penalty_materials`] is the named, ordered material palette every object
//! references (colors live here, not on objects). [`penalty_style`] is the retro 32-bit
//! visual-style descriptor (low internal resolution, pixel snapping, flat
//! shading, nearest filtering; no PBR, no dynamic shadows).
//! [`penalty_blob_shadow`] holds the three faked blob-shadow descriptors, and
//! [`penalty_style_pass::PenaltyStylePass`] bundles the light model + style the
//! render plan flat-shades world materials with. The HUD is unlit. See
//! `PASS_3_LIGHTING_AND_STYLE.md`.
//!
//! ## Pass 4 — deterministic aim + shot-power interaction
//! [`penalty_input::PenaltyInputIntent`] is the app-local deterministic input
//! contract (no browser APIs). [`penalty_interaction`] is a fixed-tick state
//! machine ([`penalty_interaction::PenaltyInteractionState`] over
//! `Aiming` / `Charging` / `LockedPreview` / …) that moves the aim reticle
//! inside the goal-mouth rectangle and charges the power meter, freezing both
//! into a [`penalty_interaction::PenaltyShotPreview`] on release. The HUD
//! ([`penalty_hud::PenaltyHudModel`]) is derived from that state. See
//! `PASS_4_AIM_AND_POWER.md`.
//!
//! ## Pass 5 — deterministic ball trajectory
//! [`penalty_interaction::PenaltyShotFlightState`] extends the machine with
//! `BallInFlight` and `ArrivedAtGoalPlane`. On the tick after a lock the ball
//! launches and follows a fixed parametric arc ([`penalty_ball`]) from the
//! penalty spot to the mapped goal-plane target, producing a
//! [`penalty_ball::PenaltyBallPose`] per tick (position, a shrinking blob
//! shadow, and a trail). The app overlays that pose onto the ball/shadow items. No
//! goal/save/miss/post is resolved. See `PASS_5_BALL_TRAJECTORY.md`.
//!
//! ## Pass 6 — deterministic goalie save volumes + contact detection
//! [`penalty_goalie`] attaches a fixed set of invisible collision volumes to
//! the static goalie (`LeftHand` / `RightHand` spheres, `Torso` / `Body`
//! boxes, in that strict priority order). Each `BallInFlight` tick the ball
//! sphere is tested against them by [`penalty_goalie::PenaltyGoalieContactDetector`],
//! producing a neutral [`penalty_goalie::PenaltyGoalieContactFrame`]
//! (`Hand` / `Torso` / `Body` / `None`) and, on contact, the new
//! `ContactDetected` state. **No save/goal/miss/post is resolved.** Debug
//! volume visualization is off by default. See `PASS_6_GOALIE_SAVE_VOLUMES.md`.
//!
//! ## Pass 7 — goalie pose clips + animated save volumes
//! [`penalty_goalie_pose`] models the goalie as a 16-part articulated primitive
//! puppet ([`penalty_goalie_pose::PenaltyGoaliePartKind`]) with world transforms
//! composed through the hierarchy, five authored dive clips
//! ([`penalty_goalie_pose::PenaltyGoaliePoseClip`]) selected by a deterministic
//! [`penalty_goalie_pose::PenaltyGoalieDiveLane`] from the locked target, and a
//! nearest-frame sampler. The Pass 6 save volumes ride on the animated
//! hands/torso/pelvis ([`penalty_goalie_pose::PenaltyGoalieAnimatedVolumeSet`]),
//! and contact detection now runs against the *posed* volumes. Still **no**
//! save/goal/miss/post resolution and no ball deflection. See
//! `PASS_7_GOALIE_POSE_CLIPS.md`.
//!
//! ## Pass 8 — deterministic shot result resolution
//! [`penalty_result`] classifies each shot into a final
//! [`penalty_result::PenaltyShotResultKind`] (`Goal`/`Save`/`Miss`/`Post`) via a
//! strict priority order — goalie contact → post/crossbar
//! ([`penalty_result::PenaltyGoalFrameVolumeSet`]) → inside the goal mouth
//! ([`penalty_result::PenaltyGoalMouth`]) → miss — producing a
//! [`penalty_result::PenaltyResolvedShotState`] and a `Resolved` state with the
//! result shown on the HUD. **The score/round/best are unchanged** and there is
//! no net wobble, post shake, or deflection. See
//! `PASS_8_SHOT_RESULT_RESOLUTION.md`.
//!
//! ## Pass 9 — scoring, round advancement, and the playable loop
//! [`penalty_scoring`] awards deterministic points per result (base + power +
//! placement + streak bonuses), and [`penalty_session::PenaltySessionState`]
//! wraps the single shot in a 5-round session: it awards once per resolved shot,
//! records round history, tracks an app-local best score, and advances through
//! `continue`/`reset` into `SessionComplete`. The HUD shows the live
//! score/round/best/award/prompt. **No persistence, no net wobble, no polish.**
//! See `PASS_9_SCORING_AND_LOOP.md`.
//!
//! ## Pass 10 — deterministic impact polish & result juice
//! [`penalty_effects`] adds tick-driven, app-local effect *descriptors* played
//! when a shot resolves (and when the session completes): net wobble (Goal),
//! post/crossbar shake (Post), a save impact flash + fake ball deflection
//! (Save), a miss drift (Miss), crowd reaction, additive camera juice, and an
//! animated result banner + score popup. All are pure functions of
//! `(result, effect tick, final pose, award)` — no physics, no particle engine,
//! and no change to Pass 8 results or Pass 9 scores. See
//! `PASS_10_IMPACT_POLISH.md`.
//!
//! ## Determinism
//! Every artifact is a pure function of compile-time constants: no wall-clock
//! time, no randomness, no unordered-map iteration. Objects are emitted into an
//! explicit `Vec` with sequential stable ids, and the render plan is a total
//! sort by `(layer, id)`. `SoccerPenaltyApp::build_stage1()` returns an equal
//! value every time.
//!
//! ## Entry point
//! [`SoccerPenaltyApp::build_stage1`] returns a [`Stage1Diorama`]
//! (objects + render plan + HUD). See `examples/print_stage1.rs` for a runnable
//! dump.

pub mod low_poly_assets;
pub mod penalty_ball;
pub mod penalty_body;
pub mod penalty_render_meshed;
pub mod penalty_blob_shadow;
// The recipe-generated art pipeline: every soccer mesh and texture is a baked
// recipe (replacing the old hand-authored `penalty_meshes` / `penalty_textures`).
pub mod recipe_meshes;
pub mod recipe_style;
pub mod recipe_textures;
pub mod penalty_effects;
pub mod penalty_goalie;
pub mod penalty_goalie_pose;
pub mod penalty_hud;
pub mod penalty_input;
pub mod penalty_interaction;
pub mod penalty_kicker;
pub mod penalty_light;
pub mod penalty_materials;
pub mod penalty_render_plan;
pub mod penalty_result;
pub mod penalty_scene;
pub mod penalty_scoring;
pub mod penalty_session;
pub mod penalty_style;
pub mod penalty_style_pass;
pub mod soccer_penalty_app;
pub mod static_diorama;

/// The browser (wasm) demo arm + the native engine-scene bridge that renders
/// the game through the real engine backend in the gallery.
pub mod web;

/// The native, `axiom-agent`-driven agent that plays a full session (gated
/// behind the `agent` feature, like the growth agent — the default gates never
/// compile it).
#[cfg(feature = "soccer-penalty-agent")]
pub mod agent;

pub use penalty_ball::{PenaltyBallPose, PenaltyBallState};
pub use penalty_goalie::{
    PenaltyGoalieContactFrame, PenaltyGoalieContactKind, PenaltyGoalieDebugDescriptor,
    PenaltyGoalieVolumeKind,
};
pub use penalty_goalie_pose::{
    PenaltyGoalieAnimation, PenaltyGoalieAnimationState, PenaltyGoalieDiveLane,
    PenaltyGoaliePartKind,
};
pub use penalty_input::PenaltyInputIntent;
pub use penalty_interaction::{PenaltyInteractionState, PenaltyShotFlightState, PenaltyShotPreview};
pub use penalty_result::{
    PenaltyShotResult, PenaltyShotResultDetail, PenaltyShotResultKind, PenaltyShotResultResolver,
};
pub use penalty_scoring::{PenaltyScoreAward, PenaltyScoreBreakdown, PenaltyScoreRule};
pub use penalty_effects::{
    PenaltyEffectDescriptor, PenaltyImpactEffectKind, PenaltyImpactEffectState,
};
pub use penalty_session::{
    PenaltyLoopState, PenaltyRoundState, PenaltySessionState, PenaltySessionSummary,
};
pub use soccer_penalty_app::{SoccerPenaltyApp, Stage1Diorama};
