//! The **single, shared** meshed render bridge: author the diorama into the
//! engine scene with real low-poly geometry instead of catalog cubes, so the
//! actors read as rounded figures.
//!
//! Every mesh and texture it registers is **generated by the recipe pipeline**
//! (`axiom-proc-mesh` / `axiom-proc-texture`) from
//! [`crate::soccer_penalty::recipe_meshes`] /
//! [`crate::soccer_penalty::recipe_textures`], baked once in
//! [`PenaltyMeshedScene::install`] and registered through the ordinary
//! `add_mesh_data` / `add_texture_data` hooks. The
//! app hand-authors no geometry or pixels — nothing is rendered "on its own".
//!
//! This is the *one* path both consumers use, so the convergence champion and the
//! live gallery can never diverge:
//!
//! * the **headless champion** ([`soccer_meshed_app`]) — `axiom-shot` / the
//!   visual-convergence loop — builds it once and ticks it, and
//! * the **live browser gallery** ([`crate::soccer_penalty::web::soccer_penalty_start`])
//!   re-authors it every frame.
//!
//! Both go through [`PenaltyMeshedScene`]: the same mesh library, the same
//! shape→mesh mapping, the same per-object spawn.
//!
//! Why not the `setup`/`reauthor` closure. The live/browser path historically
//! authored through that closure, whose `Assets<Mesh>` can only name the catalog
//! cube/sphere/plane — the `Mesh` enum is deliberately fieldless so the engine
//! resolves it branchlessly by table index, so it *cannot* carry custom geometry.
//! Real geometry has its own sanctioned channel: `RunningApp::add_mesh_data`
//! (which stores resolved geometry directly). So this scene registers the mesh
//! library once via that channel and drives per-frame updates with runtime
//! `spawn`/`despawn` — never `reauthor`, which would rebuild the mesh store from
//! the catalog-only closure and wipe the custom meshes.

use std::collections::{BTreeMap, HashMap};

use axiom::prelude::*;
use axiom_math::{Mat4, Quat};
use axiom_proc_mesh::ProcMeshApi;
use axiom_proc_texture::ProcTextureApi;
use axiom_recipe::RecipeGraph;

use crate::soccer_penalty::low_poly_assets::{PrimitiveShape, Rgba};
use crate::soccer_penalty::penalty_body::{self, BodyPart};
use crate::soccer_penalty::penalty_materials::{material, PenaltyMaterialId};
use crate::soccer_penalty::penalty_render_plan::PenaltyRenderContent;
use crate::soccer_penalty::penalty_scene::DioramaRole;
use crate::soccer_penalty::recipe_style::SoccerRecipeStyle;
use crate::soccer_penalty::{recipe_meshes, recipe_textures};
use crate::soccer_penalty::soccer_penalty_app::Stage1Diorama;
use crate::soccer_penalty::static_diorama::CameraConfig;

const WIDTH: u32 = 960;
const HEIGHT: u32 = 600;

/// A finite `Ratio` from a colour channel (clamped, so always valid).
fn ch(value: f32) -> Ratio {
    Ratio::new(value.clamp(0.0, 1.0)).expect("clamped colour channel is finite")
}

/// Bake one mesh recipe and register it as engine geometry, returning its handle.
/// The recipe pipeline emits neutral vertex buffers the same shape `add_mesh_data`
/// takes, so the app never hand-authors a mesh.
fn bake_mesh(app: &mut RunningApp, api: &ProcMeshApi, recipe: &RecipeGraph, seed: u64) -> Handle<Mesh> {
    let mb = api.bake(recipe, seed).expect("soccer mesh recipe bakes");
    // A skinned buffer (MetaSurface body) carries its joint/weight streams into a
    // skinned MeshData so it uploads through the skinning pipeline; every other
    // recipe is static geometry.
    let data = if mb.is_skinned() {
        MeshData::new_skinned(
            mb.positions().to_vec(),
            mb.normals().to_vec(),
            mb.uvs().to_vec(),
            mb.joints().to_vec(),
            mb.weights().to_vec(),
            mb.indices().to_vec(),
        )
    } else {
        MeshData::new(
            mb.positions().to_vec(),
            mb.normals().to_vec(),
            mb.uvs().to_vec(),
            mb.indices().to_vec(),
        )
    };
    app.add_mesh_data(data).expect("baked mesh registers")
}

/// Bake one texture recipe and register it as engine texture data, returning its
/// id (0 = none). The recipe bakes to an RGBA8 buffer `add_texture_data` takes, so
/// the app never hand-authors pixels.
fn bake_texture(app: &mut RunningApp, api: &ProcTextureApi, recipe: &RecipeGraph, seed: u64) -> u64 {
    let buf = api.bake(recipe, seed).expect("soccer texture recipe bakes");
    let (w, h) = (buf.width(), buf.height());
    app.add_texture_data(w, h, buf.into_pixels()).expect("baked texture registers").id()
}

/// Keep flat quad/line slabs thin without collapsing to a zero extent.
fn nonzero(s: Vec3) -> Vec3 {
    let c = |v: f32| if v.abs() < 1.0e-3 { 0.01 } else { v };
    Vec3::new(c(s.x), c(s.y), c(s.z))
}

/// The structural role of one posed rig part, derived from its label regardless
/// of the rig's naming scheme.
///
/// Two rigs disagree on part names (the kicker uses `l_upper_arm`, the goalie
/// `upperarm.left`; the kicker's torso is `chest`, the goalie's is `torso`; the
/// kicker has no hand parts at all). The old brittle substring test mapped
/// `l_upper_arm` to a plain cube (it never contained `"upperarm"`). This role is
/// classified from a *normalized* label — lowercased with `.`/`_` stripped — so
/// `l_upper_arm` and `upperarm.left` both land on [`PartRole::Limb`].
#[derive(Clone, Copy, Debug, PartialEq, Eq)]
enum PartRole {
    /// The ball — a true sphere (`size` is its radius).
    Ball,
    /// An arm or leg segment (upper arm, forearm, thigh, shin) — a rounded,
    /// jointed capsule (cylinder body + a sphere at each end).
    Limb,
    /// A head — a sphere.
    Head,
    /// A hand — a sphere (only the goalie rig emits these; the kicker's fists are
    /// the distal joint spheres of its forearms).
    Hand,
    /// A torso, chest, or pelvis — a softened (bevelled) box.
    Torso,
    /// A foot — a softened (bevelled) box.
    Foot,
    /// A hair cap — a plain box (a flat cap, as authored).
    Hair,
    /// Anything else (structure: posts, wall, crowd, ad boards, ground, net) — a
    /// crisp box.
    Cube,
}

/// Classify a posed part into its structural [`PartRole`] from its shape and its
/// label. The label is normalized (lowercased, `.`/`_` removed) so both rig
/// naming schemes (`l_upper_arm` and `upperarm.left`) classify identically.
fn classify(shape: PrimitiveShape, label: &str) -> PartRole {
    let norm = label.to_lowercase().replace(['.', '_'], "");
    let has = |needle: &str| norm.contains(needle);
    let is_limb = has("upperarm") || has("forearm") || has("thigh") || has("shin");
    match shape {
        PrimitiveShape::FacetedBall => PartRole::Ball,
        _ if is_limb => PartRole::Limb,
        _ if has("hand") => PartRole::Hand,
        _ if has("head") => PartRole::Head,
        _ if has("foot") => PartRole::Foot,
        _ if has("hair") => PartRole::Hair,
        _ if has("torso") || has("chest") || has("pelvis") => PartRole::Torso,
        _ => PartRole::Cube,
    }
}

/// One drawable piece of a posed part, in the part's **local** (bone) frame: a
/// mesh and the local transform that places it relative to the part's world
/// translate∘rotate. A simple part yields one sub-part (a scaled mesh at the
/// origin); a limb yields three (a cylinder body plus a sphere at each bone end).
#[derive(Clone, Copy, Debug)]
struct SubPart {
    mesh: Handle<Mesh>,
    local: Transform,
}

/// The drawable sub-parts of one posed part, in its local bone frame.
///
/// A **limb** becomes the classic capsule-and-ball: a cylinder body scaled to the
/// limb's footprint plus a sphere at each end (proximal + distal joint). The
/// joint spheres fill the gaps between adjacent bone segments (shoulder/elbow/
/// wrist, hip/knee/ankle) and round the limb's caps; the distal forearm sphere
/// doubles as the kicker's fist (its rig has no hand parts). They sit at
/// `±size.y/2` along the local Y — the axis the part's box extends along its bone
/// — so the part's world rotation orients them onto the joint. **Head/hand** →
/// sphere; **torso/foot** → softened bevel box; **hair/other** → crisp box; the
/// **ball** → sphere (radius→diameter).
/// Group athletes' parts by kit material (deterministic `BTreeMap` order), each
/// part as a [`BodyPart`] — shared by the bake and the per-frame skinning pass so
/// their capsule/joint order matches exactly.
fn body_groups(athletes: &[WorldObj]) -> Vec<(PenaltyMaterialId, Vec<BodyPart>)> {
    let mut groups: BTreeMap<PenaltyMaterialId, Vec<BodyPart>> = BTreeMap::new();
    athletes.iter().for_each(|o| {
        groups
            .entry(o.material)
            .or_default()
            .push(BodyPart { position: o.position, rotation: o.rotation, size: o.size });
    });
    groups.into_iter().collect()
}

/// A part's world matrix (translate ∘ rotate; the capsule shape lives in the baked
/// geometry, so no scale) — the transform its MetaSurface capsule was placed at.
fn part_world(p: &BodyPart) -> Mat4 {
    Transform::new(p.position, p.rotation, Vec3::ONE).to_matrix()
}

fn sub_parts(role: PartRole, size: Vec3, lib: MeshLib) -> Vec<SubPart> {
    let one = |mesh: Handle<Mesh>, scale: Vec3| vec![SubPart { mesh, local: Transform::from_scale(scale) }];
    match role {
        PartRole::Ball => one(lib.sphere, size.mul_scalar(2.0)),
        PartRole::Limb => {
            // Limb radius ≈ the average half-extent of the box's cross-section,
            // inset to 0.82 so the rounded tube reads as a *lean* athletic limb
            // rather than an inflated balloon that fills the whole box. The
            // reference #10 has slender, tapered arms/legs; a capsule filling the
            // full cross-section reads chunky and bulbous (worst at the bent elbow/
            // knee, where two full-width joint spheres overlap). Inset shrinks the
            // tube and its joint spheres together (both derive from `radius`), so
            // the capsule stays coherent, just slimmer.
            let radius = (size.x + size.z) * 0.25 * 0.82;
            let diameter = radius * 2.0;
            // The unit capsule's bbox is (0.8, 1.0, 0.8); scale its footprint to
            // the limb diameter and its height to the limb length.
            let body = Vec3::new(diameter / 0.8, size.y, diameter / 0.8);
            // The unit sphere's bbox is 1×1×1; scale to the limb diameter so each
            // joint ball is as wide as the tube it caps.
            let joint = Vec3::new(diameter, diameter, diameter);
            let half = size.y * 0.5;
            vec![
                SubPart { mesh: lib.capsule, local: Transform::from_scale(body) },
                SubPart {
                    mesh: lib.sphere,
                    local: Transform::new(Vec3::new(0.0, half, 0.0), Quat::IDENTITY, joint),
                },
                SubPart {
                    mesh: lib.sphere,
                    local: Transform::new(Vec3::new(0.0, -half, 0.0), Quat::IDENTITY, joint),
                },
            ]
        }
        PartRole::Head | PartRole::Hand => one(lib.sphere, nonzero(size)),
        PartRole::Torso | PartRole::Foot => one(lib.bevel, nonzero(size)),
        PartRole::Hair | PartRole::Cube => one(lib.cube, nonzero(size)),
    }
}

/// The registered low-poly mesh library (one handle per shape family).
#[derive(Clone, Copy, Debug)]
struct MeshLib {
    cube: Handle<Mesh>,
    sphere: Handle<Mesh>,
    capsule: Handle<Mesh>,
    bevel: Handle<Mesh>,
}

/// The registered retro 32-bit pixel-art texture ids (0 = none), by surface kind.
#[derive(Clone, Copy, Debug)]
struct TexLib {
    crowd: u64,
    ad_axiom: u64,
    ad_generic: u64,
    jersey: u64,
    keeper: u64,
    ball: u64,
    skin: u64,
    turf: u64,
}

/// The shared meshed scene: the mesh + texture libraries, a
/// (colour, texture)→material cache (so a stable palette of materials is
/// registered before the live backend snapshots them, and no material leaks per
/// frame), and the entities spawned last frame (despawned before the next pass).
#[derive(Debug)]
pub struct PenaltyMeshedScene {
    lib: MeshLib,
    tex: TexLib,
    palette: HashMap<([u8; 3], u64), Handle<Material>>,
    /// The entities spawned per object, keyed by the object's `(label, ordinal)`
    /// and tagged with a content hash — a persistent per-frame cache. Re-authoring
    /// reuses the entities of any object whose content is unchanged (the ~170
    /// static scenery pieces), so only the objects that actually moved (the ball,
    /// net wobble, impact effects) despawn + respawn. This turns the whole-scene
    /// rebuild the live loop did every frame into an incremental diff. The one-shot
    /// offscreen champion starts with an empty cache, so it spawns everything in
    /// order exactly as before — its render stays byte-identical.
    cache: HashMap<(&'static str, u32), CachedObject>,
    /// The athletes' once-baked skinned bodies (one continuous MetaSurface per kit
    /// material). Baked at the bind pose on the first authored frame, then deformed
    /// each frame by a joint palette — never re-baked.
    skinned_bodies: Vec<SkinnedBody>,
    /// When true the athletes render as continuous **skinned** MetaSurface bodies
    /// (GPU linear-blend skinning: bake once, deform per frame). The offscreen
    /// champion (`axiom-shot`) uses this. The live browser loop leaves it false and
    /// renders the athletes as pre-baked articulated parts until the skinned draw is
    /// threaded through the `run_web_multi` present path (a follow-up); box-man keeps
    /// the live game rendering + fast today.
    skinned: bool,
}

/// One object's cached spawn: the content hash it was spawned from and the
/// entities it produced. Reused across frames while the hash matches (an unmoved
/// static object), despawned + rebuilt when it changes or disappears.
#[derive(Debug)]
struct CachedObject {
    hash: u64,
    entities: Vec<Entity>,
}

/// One athlete's once-baked skinned body: the mesh, its material, and the inverse
/// bind-pose world matrix of each of its capsules (in group order) — used to build
/// the per-frame joint palette (`current_world * bind_inv`).
#[derive(Debug)]
struct SkinnedBody {
    mesh: Handle<Mesh>,
    material: Handle<Material>,
    bind_inv: Vec<Mat4>,
}

impl PenaltyMeshedScene {
    /// Bake the mesh + texture **recipes** and register the results into `app`,
    /// priming an empty scene. Every mesh and texture is generated by the recipe
    /// pipeline (`axiom-proc-mesh` / `axiom-proc-texture`) from
    /// [`SoccerRecipeStyle`] and registered through the ordinary
    /// `add_mesh_data` / `add_texture_data` hooks — the app authors no geometry or
    /// pixels of its own.
    pub fn install(app: &mut RunningApp) -> Self {
        let style = SoccerRecipeStyle::stadium();
        let mesh_api = ProcMeshApi::new();
        let tex_api = ProcTextureApi::new();
        let lib = MeshLib {
            cube: bake_mesh(app, &mesh_api, &recipe_meshes::box_mesh(), style.seed),
            sphere: bake_mesh(app, &mesh_api, &recipe_meshes::sphere_mesh(), style.seed),
            capsule: bake_mesh(app, &mesh_api, &recipe_meshes::capsule_mesh(), style.seed),
            bevel: bake_mesh(app, &mesh_api, &recipe_meshes::bevel_box_mesh(), style.seed),
        };
        let tex = TexLib {
            crowd: bake_texture(app, &tex_api, &recipe_textures::crowd(&style), style.seed),
            ad_axiom: bake_texture(app, &tex_api, &recipe_textures::ad_axiom(&style), style.seed),
            ad_generic: bake_texture(app, &tex_api, &recipe_textures::ad_generic(&style), style.seed),
            jersey: bake_texture(app, &tex_api, &recipe_textures::jersey(&style), style.seed),
            keeper: bake_texture(app, &tex_api, &recipe_textures::keeper(&style), style.seed),
            ball: bake_texture(app, &tex_api, &recipe_textures::ball(&style), style.seed),
            skin: bake_texture(app, &tex_api, &recipe_textures::skin(&style), style.seed),
            turf: bake_texture(app, &tex_api, &recipe_textures::turf(&style), style.seed),
        };
        Self { lib, tex, palette: HashMap::new(), cache: HashMap::new(), skinned_bodies: Vec::new(), skinned: false }
    }

    /// Render the athletes as continuous **skinned** MetaSurface bodies (bake once,
    /// deform per frame by a joint palette). Used by the one-shot offscreen champion
    /// (`axiom-shot`); the live loop leaves this off (box-man) until the skinned draw
    /// is threaded through the `run_web_multi` present path.
    pub fn with_skinned_bodies(mut self) -> Self {
        self.skinned = true;
        self
    }

    /// The retro 32-bit texture id for one object's role/label (0 = flat, no texture).
    fn texture_for(&self, role: DioramaRole, label: &str) -> u64 {
        match role {
            DioramaRole::Field => self.tex.turf,
            DioramaRole::CrowdCard => self.tex.crowd,
            DioramaRole::AdBoard => {
                if label == "ad.board.axiom" {
                    self.tex.ad_axiom
                } else {
                    self.tex.ad_generic
                }
            }
            DioramaRole::Kicker => self.body_texture(label, self.tex.jersey),
            DioramaRole::Goalie => self.body_texture(label, self.tex.keeper),
            DioramaRole::Ball => (label == "ball").then_some(self.tex.ball).unwrap_or(0),
            _ => 0,
        }
    }

    /// Body-part texture: the kit on the torso, skin on head/hands, flat elsewhere.
    fn body_texture(&self, label: &str, kit: u64) -> u64 {
        if label.ends_with(".torso") {
            kit
        } else if label.ends_with(".head") || label.contains("hand") {
            self.tex.skin
        } else {
            0
        }
    }

    /// Set the fixed camera and key light once (call after [`Self::install`]).
    pub fn set_view(&self, app: &mut RunningApp, cam: CameraConfig) {
        app.set_camera(
            Camera::perspective(PerspectiveProjection {
                fov_y: Angle::degrees(cam.fov_y_degrees),
                near: Meters::new(cam.near).expect("camera near plane is finite"),
                far: Meters::new(cam.far).expect("camera far plane is finite"),
            }),
            Transform::from_translation(cam.eye)
                .looking_at(cam.target, cam.up)
                .unwrap_or_else(|_| Transform::from_translation(cam.eye)),
        );
        // A warm key light that RAKES in low from the upper-behind-left (matching
        // the baked flat-shading model's direction) so it models the vertical
        // figure faces — jerseys, keeper, player fronts — with a golden stadium-sun
        // cast, instead of a steep top-light that only nukes the up-facing pitch
        // flat while the athletes fall to the dim cool ambient.
        app.add_light(
            DirectionalLight {
                direction: Vec3::new(-0.50, -0.66, -0.56),
                color: Color::linear_rgb(ch(1.0), ch(0.95), ch(0.83)),
                intensity: ch(1.25),
            },
            Transform::IDENTITY,
        );
        // A cool sky-FILL light. The engine's default hemisphere ambient is a dark
        // floor (sky ~0.4, ground ~0.15), so every face the warm key misses — the
        // shadow side of the athletes, the keeper's front, the crowd/stand cards —
        // crushes toward black, while the reference is a high-key sunlit stadium
        // whose strong sky bounce lifts the shadows into open daylight. This second
        // directional rakes in from the opposite (upper-front-left) side, shallower
        // and dimmer than the key and tinted cool sky-blue, to lift those shadowed
        // faces and cut the harsh key-to-fill contrast — the classic key + fill
        // pairing. The single 5x5 PCF shadow stays on the warm key above.
        app.add_light(
            DirectionalLight {
                direction: Vec3::new(0.46, -0.52, 0.42),
                color: Color::linear_rgb(ch(0.60), ch(0.70), ch(0.86)),
                intensity: ch(0.55),
            },
            Transform::IDENTITY,
        );
    }

    /// A cached lit material for `color` (registered once, reused thereafter), so
    /// the material set the live backend snapshots at startup stays stable.
    fn material_for(&mut self, app: &mut RunningApp, color: Rgba, tex_id: u64) -> Handle<Material> {
        let key = (
            [
                (color.r.clamp(0.0, 1.0) * 255.0) as u8,
                (color.g.clamp(0.0, 1.0) * 255.0) as u8,
                (color.b.clamp(0.0, 1.0) * 255.0) as u8,
            ],
            tex_id,
        );
        *self.palette.entry(key).or_insert_with(|| {
            // The texture (when present) modulates the flat `shaded_color` tint —
            // albedo × base colour — so the retro 32-bit shading survives under the texture.
            let base = Material::lit(Color::linear_rgb(ch(color.r), ch(color.g), ch(color.b)));
            let material = if tex_id != 0 { base.with_custom_texture(tex_id) } else { base };
            app.add_material(material)
        })
    }

    /// Re-author the diorama as an **incremental diff**: every object whose content
    /// is unchanged since last frame (the ~170 static scenery pieces) keeps its
    /// entities; only objects that actually moved (the ball, net wobble, impact
    /// effects) despawn + respawn. This replaces the whole-scene rebuild the live
    /// loop did every frame — the dominant per-frame cost. Objects draw in the
    /// plan's back-to-front order, each nudged a hair toward the camera so
    /// near-coplanar ground/net quads win the depth test; camera + light are set
    /// once. The one-shot offscreen champion starts with an empty cache, so it
    /// spawns everything in order exactly as before — its render stays
    /// byte-identical.
    pub fn author(&mut self, app: &mut RunningApp, frame: &Stage1Diorama) {
        let cam = frame.render_plan.camera;
        // Collect first so the immutable borrow of `frame` doesn't overlap the
        // mutable `self`/`app` borrows below.
        let objects: Vec<WorldObj> = frame
            .render_plan
            .items
            .iter()
            .filter_map(|item| match item.content {
                PenaltyRenderContent::World { role, shape, position, rotation, size, material, shaded_color, .. } => {
                    Some(WorldObj { role, label: item.label, shape, position, rotation, size, material, color: shaded_color })
                }
                _ => None,
            })
            .collect();

        // The athletes are one continuous, **skinned** MetaSurface body per kit
        // material — baked ONCE (bind pose = the first authored frame), then
        // deformed each frame by a joint palette (each part's current-vs-bind
        // transform). No per-frame marching cubes, no per-frame mesh registration;
        // the bodies ride the bind-time GPU upload and only their palette changes.
        let skinned = self.skinned;
        let athletes: Vec<WorldObj> = objects.iter().copied().filter(|o| is_athlete(o.role)).collect();
        skinned.then(|| {
            self.skinned_bodies.is_empty().then(|| self.bake_skinned_bodies(app, &athletes));
            self.submit_skinned_bodies(app, &athletes);
        });

        // Diff-author every non-athlete object against last frame's cache, keyed by
        // `(label, ordinal)`. Unchanged content → reuse the entities; changed → swap
        // them; new → spawn. When `skinned` is off the box-man athletes come through
        // here too. The depth-bias `index` still walks EVERY object so the
        // non-athlete bias values stay byte-identical to a full re-author.
        let mut next: HashMap<(&'static str, u32), CachedObject> = HashMap::new();
        let mut ordinals: HashMap<&'static str, u32> = HashMap::new();
        let mut index = 0u64;
        objects.into_iter().for_each(|o| {
            (!skinned || !is_athlete(o.role)).then(|| {
                let ord = ordinals.entry(o.label).or_insert(0);
                let key = (o.label, *ord);
                *ord += 1;
                let hash = object_hash(&o, index);
                let cached = match self.cache.remove(&key) {
                    Some(c) if c.hash == hash => c,
                    Some(c) => {
                        c.entities.into_iter().for_each(|e| {
                            app.despawn(e);
                        });
                        CachedObject { hash, entities: self.spawn_object(app, &o, cam, index) }
                    }
                    None => CachedObject { hash, entities: self.spawn_object(app, &o, cam, index) },
                };
                next.insert(key, cached);
            });
            index += 1;
        });
        // Whatever is left in the old cache is an object that vanished this frame
        // (e.g. the net wobble ending) — despawn it.
        self.cache.drain().for_each(|(_, c)| {
            c.entities.into_iter().for_each(|e| {
                app.despawn(e);
            });
        });
        self.cache = next;
    }

    /// Spawn one world object's sub-parts at its depth-biased world transform and
    /// return the spawned entities. `index` is the object's position in the draw
    /// walk, driving the tiny toward-camera nudge that breaks coplanar depth ties.
    /// Shared by the initial author and every diff re-spawn.
    fn spawn_object(&mut self, app: &mut RunningApp, o: &WorldObj, cam: CameraConfig, index: u64) -> Vec<Entity> {
        let to_eye = cam.eye.subtract(o.position);
        let dir = to_eye.mul_scalar(1.0 / to_eye.length().max(1.0e-6));
        let biased = o.position.add(dir.mul_scalar(index as f32 * 0.0015));
        let mat = self.material_for(app, o.color, self.texture_for(o.role, o.label));
        // The part's world placement: translate ∘ rotate. Each sub-part carries its
        // own local transform (scale, plus a bone-frame offset for limb joints),
        // composed *inside* the part rotation.
        let base = Transform::combine(Transform::from_translation(biased), Transform::from_rotation(o.rotation));
        sub_parts(classify(o.shape, o.label), o.size, self.lib)
            .into_iter()
            .map(|sp| app.spawn(Spawn::new(Transform::combine(base, sp.local), sp.mesh, mat)))
            .collect()
    }

    /// Bake the athletes' skinned bodies **once** at the bind pose: group each
    /// athlete's parts by kit material, bake one [`penalty_body`] `MetaSurface`
    /// (auto-weighted to its own capsule skeleton) per group, and remember each
    /// group's material handle plus the inverse of every part's bind-pose world
    /// transform. Called on the first authored frame; the geometry never re-bakes.
    fn bake_skinned_bodies(&mut self, app: &mut RunningApp, athletes: &[WorldObj]) {
        let api = ProcMeshApi::new();
        let mut recipe_id = recipe_meshes::ids::BODY_BASE;
        for (id, parts) in body_groups(athletes) {
            let mesh = bake_mesh(app, &api, &penalty_body::body_recipe(recipe_id, &parts), 0);
            let material = self.material_for(app, material(id).base_color, 0);
            let bind_inv = parts.iter().map(|p| part_world(p).inverse().unwrap_or(Mat4::IDENTITY)).collect();
            self.skinned_bodies.push(SkinnedBody { mesh, material, bind_inv });
            recipe_id += 1;
        }
    }

    /// Submit each skinned body for this frame: a joint palette whose `k`-th matrix
    /// is `current_world(part_k) * bind_world(part_k)^-1` deforms the once-baked
    /// surface from its bind pose to the current pose (the MetaSurface auto-weights
    /// fuse the joints via linear blend skinning). No geometry is regenerated.
    fn submit_skinned_bodies(&self, app: &mut RunningApp, athletes: &[WorldObj]) {
        for (body, (_id, parts)) in self.skinned_bodies.iter().zip(body_groups(athletes)) {
            let palette: Vec<Mat4> = parts
                .iter()
                .zip(body.bind_inv.iter())
                .map(|(p, &inv)| part_world(p).multiply(inv))
                .collect();
            app.submit_skinned_draw(body.mesh, body.material, Transform::IDENTITY, &palette);
        }
    }
}

/// One collected world primitive from the render plan.
#[derive(Clone, Copy)]
struct WorldObj {
    role: DioramaRole,
    label: &'static str,
    shape: PrimitiveShape,
    position: Vec3,
    rotation: Quat,
    size: Vec3,
    material: PenaltyMaterialId,
    color: Rgba,
}

/// Whether a role is an athlete (skinned as a continuous body) rather than
/// scenery (drawn per primitive).
fn is_athlete(role: DioramaRole) -> bool {
    matches!(role, DioramaRole::Kicker | DioramaRole::Goalie)
}

/// A content hash over exactly the fields that determine an object's spawned
/// entities — its draw `index` (depth bias), world placement, size and colour.
/// Shape / role / texture are constant for a given `label`, which is already part
/// of the cache key, so they need not be hashed. Two frames with the same hash for
/// the same `(label, ordinal)` spawn identical entities, so the diff reuses them.
/// Floats are hashed by bit pattern for exact (bit-for-bit) reuse decisions.
fn object_hash(o: &WorldObj, index: u64) -> u64 {
    use std::hash::{Hash, Hasher};
    let mut h = std::collections::hash_map::DefaultHasher::new();
    index.hash(&mut h);
    [
        o.position.x, o.position.y, o.position.z,
        o.size.x, o.size.y, o.size.z,
        o.rotation.x, o.rotation.y, o.rotation.z, o.rotation.w,
        o.color.r, o.color.g, o.color.b, o.color.a,
    ]
    .iter()
    .for_each(|f| f.to_bits().hash(&mut h));
    h.finish()
}

/// Build the empty meshed app shell (window + clear colour + default plugins).
pub fn soccer_meshed_shell() -> RunningApp {
    let mut app = App::new()
        .window(
            Window::new(WIDTH, HEIGHT)
                // Warm dark neutral, not cold navy: the old (0.07,0.10,0.18) clear
                // colour tinted the whole uncovered upper background cool blue,
                // fighting the reference's sunlit warmth. A warm charcoal matches
                // the stand behind it and lets the frame read warm off the grade.
                .with_clear_color(Color::linear_rgb(ch(0.10), ch(0.09), ch(0.08))),
        )
        .add_plugins(DefaultPlugins)
        .build();
    // Author a bright DAYLIGHT hemisphere ambient, replacing the dim engine
    // default (sky ~0.4 / ground ~0.16) both render paths otherwise hardcode. The
    // reference is a high-key sunlit stadium, so the fill must lift every
    // key-missed face — the athletes' shadow sides, the keeper's front, and the
    // whole crowd/stand backdrop — off the near-black floor the dim default
    // crushed them to. The GROUND term is the fill the vertical & camera-facing
    // faces draw (a hemisphere face at normal.y≈0 mixes half sky / half ground),
    // so the crushed background stands and shadow sides were pinned by the old
    // dim, warm ground floor (0.45/0.42/0.37): a ~0.30-albedo stand card came out
    // near black. Lift the ground toward a cool, near-sky daylight bounce so those
    // faces read as open shade, not night — the up-facing pitch (which draws the
    // brighter sky term) is untouched, so this lifts the darks without blowing the
    // grass. Strength is folded into the tints (a plain mix, no scale).
    app.set_ambient(FrameAmbient::new([0.66, 0.71, 0.80], [0.60, 0.62, 0.64]));
    app
}

/// Build the headless meshed [`RunningApp`] for one static frame — the
/// convergence champion (`axiom-shot`). Identical authoring to the live gallery.
pub fn soccer_meshed_app(frame: Stage1Diorama) -> RunningApp {
    let mut app = soccer_meshed_shell();
    // One-shot offscreen render (the convergence champion): the athletes are one
    // continuous skinned MetaSurface body, baked once and deformed by a joint palette.
    let mut scene = PenaltyMeshedScene::install(&mut app).with_skinned_bodies();
    scene.set_view(&mut app, frame.render_plan.camera);
    scene.author(&mut app, &frame);
    app
}
